version: '3.7'

services:

  akaunting:
    container_name: akaunting
    build:
      dockerfile: v.Dockerfile
      context: .
    ports:
      - 8088:80
    volumes:
      - akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mysql:latest
    ports:
      -8033:3306
    volumes:
      - akaunting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

volumes:
  akaunting-data:
  akaunting-db:
